fix: Update command to fix incorrect path
* while execution due to single quote of script causing the issue of unable to access jarfile
Error: Unable to access jarfile 'F:\...\node_modules\nod
e-key-sender\jar\key-sender.jar'
this patch will fix the corresponding issue.

Tested on windows, working fine.